In [3]:
from pathlib import Path
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [4]:
#data = Path('./Resources/combined_data.csv')
data = Path('./Resources/CombinedTop5_chg.csv')
df = pd.read_csv(data)
df.head()

order_name family_name  datetime  individuals  tempmax  tempmin  \
0  COLEOPTERA   CARABIDAE     37822            2     76.9     60.9   
1  COLEOPTERA   CARABIDAE     36698            3     86.0     64.1   
2  COLEOPTERA   CARABIDAE     39243            1     81.7     60.4   
3  COLEOPTERA   CARABIDAE     33787            1     71.2     58.8   
4  COLEOPTERA   CARABIDAE     34112            1     73.3     55.2   

   temp_daily  humidity  
0        69.9      69.9  
1        75.6      67.5  
2        71.9      55.4  
3        65.5      59.2  
4        63.3      66.8

In [5]:
# Segment the features from the target
y = df["individuals"]
#X = df.drop(columns=["order_name", "family_name", "datetime", "individuals", "tempmax","tempmin"])
X = df.drop(columns=["order_name", "family_name", "datetime", "individuals", "tempmax","tempmin", "temp_daily"])

In [6]:
# Use the train_test_split function to create training and testing subsets
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.2, random_state=42)
X_train.shape

(24926, 1)

In [7]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators= 10, random_state= 0)
regressor.fit(X_train, y_train)

RandomForestRegressor(n_estimators=10, random_state=0)

In [8]:
y_pred = regressor.predict(X_test)

y_pred

array([4.32556133, 6.89110319, 6.14699717, ..., 2.18903579, 1.67439394,
       2.36594928])

In [9]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

-0.016017638832902525

https://stats.stackexchange.com/questions/12900/when-is-r-squared-negative

R2  compares the fit of the chosen model with that of a horizontal straight line (the null hypothesis). If the chosen model fits worse than a horizontal line, then R2 is negative. Note that R2 is not always the square of anything, so it can have a negative value without violating any rules of math. R2 is negative only when the chosen model does not follow the trend of the data, so fits worse than a horizontal line.

Example: fit data to a linear regression model constrained so that the Y intercept must equal 1500.

enter image description here

The model makes no sense at all given these data. It is clearly the wrong model, perhaps chosen by accident.

The fit of the model (a straight line constrained to go through the point (0,1500)) is worse than the fit of a horizontal line. Thus the sum-of-squares from the model (SSres) is larger than the sum-of-squares from the horizontal line (SStot).

If R2 is computed as 1−SSresSStot. (here, SSres = residual error.)
When SSres is greater than SStot, that equation could compute a negative value for R2, if the value of the coeficient is greater than 1.

With linear regression with no constraints, R2 must be positive (or zero) and equals the square of the correlation coefficient, r. A negative R2 is only possible with linear regression when either the intercept or the slope are constrained so that the "best-fit" line (given the constraint) fits worse than a horizontal line. With nonlinear regression, the R2 can be negative whenever the best-fit model (given the chosen equation, and its constraints, if any) fits the data worse than a horizontal line.

Bottom line: a negative R2 is not a mathematical impossibility or the sign of a computer bug. It simply means that the chosen model (with its constraints) fits the data really poorly.

In [10]:
from pathlib import Path
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [11]:
#data = Path('./Resources/combined_data.csv')
data = Path('./Resources/topfive_coleoptera.csv')
df = pd.read_csv(data)
df.head()

order_name family_name    datetime  individuals  tempmax  tempmin  \
0  COLEOPTERA   CARABIDAE  2003-07-20            2     76.9     60.9   
1  COLEOPTERA   CARABIDAE  2000-06-21            3     86.0     64.1   
2  COLEOPTERA   CARABIDAE  2007-06-10            1     81.7     60.4   
3  COLEOPTERA   CARABIDAE  1992-07-02            1     71.2     58.8   
4  COLEOPTERA   CARABIDAE  1993-05-23            1     73.3     55.2   

   temp_daily  humidity  
0        69.9      69.9  
1        75.6      67.5  
2        71.9      55.4  
3        65.5      59.2  
4        63.3      66.8

In [12]:
# Segment the features from the target
y = df["individuals"]
#X = df.drop(columns=["order_name", "family_name", "datetime", "individuals", "tempmax","tempmin"])
X = df.drop(columns=["order_name", "family_name", "datetime", "individuals", "tempmax","tempmin", "temp_daily"])

In [13]:
# Use the train_test_split function to create training and testing subsets
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.2, random_state=42)
X_train.shape

(3125, 1)

In [14]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators= 10, random_state= 0)
regressor.fit(X_train, y_train)

RandomForestRegressor(n_estimators=10, random_state=0)

In [15]:
y_pred = regressor.predict(X_test)

y_pred

array([ 2.92367602,  5.10590059, 10.70725284,  6.7400091 ,  6.03571429,
        1.85871856,  1.        , 29.13853353, 10.87192818,  2.1518254 ,
        1.34833333,  1.21595238,  5.28420776,  2.16249452,  2.41090909,
        3.7924529 , 11.9312909 , 14.51328801, 10.3869697 ,  4.63199758,
        2.59964286,  3.63495169,  2.14606643,  2.96575304,  4.1065873 ,
        3.48722222,  4.63199758,  1.68453297,  1.58333333,  2.93061811,
        3.12888008,  2.14606643,  3.91029824, 14.51328801,  4.45776769,
        2.16249452,  6.36377178,  1.68453297, 10.70725284,  4.75525021,
        8.88527545,  4.25475685,  3.39280303,  9.11387013,  4.42524869,
        2.16249452,  7.12461035,  2.62797619,  2.02332321,  4.24344017,
        2.84      , 10.70725284, 44.61980544,  5.10590059,  1.21595238,
       10.48928571,  2.77930597, 10.48928571,  2.02332321,  4.16806429,
        6.51301126,  4.29607287,  4.33825033,  4.45776769,  4.74859818,
        9.11387013,  6.26557441,  1.95527778,  2.87026144,  2.15

In [16]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

-0.08585033350866156

https://stats.stackexchange.com/questions/12900/when-is-r-squared-negative

R2  compares the fit of the chosen model with that of a horizontal straight line (the null hypothesis). If the chosen model fits worse than a horizontal line, then R2 is negative. Note that R2 is not always the square of anything, so it can have a negative value without violating any rules of math. R2 is negative only when the chosen model does not follow the trend of the data, so fits worse than a horizontal line.

Example: fit data to a linear regression model constrained so that the Y intercept must equal 1500.

enter image description here

The model makes no sense at all given these data. It is clearly the wrong model, perhaps chosen by accident.

The fit of the model (a straight line constrained to go through the point (0,1500)) is worse than the fit of a horizontal line. Thus the sum-of-squares from the model (SSres) is larger than the sum-of-squares from the horizontal line (SStot).

If R2 is computed as 1−SSresSStot. (here, SSres = residual error.)
When SSres is greater than SStot, that equation could compute a negative value for R2, if the value of the coeficient is greater than 1.

With linear regression with no constraints, R2 must be positive (or zero) and equals the square of the correlation coefficient, r. A negative R2 is only possible with linear regression when either the intercept or the slope are constrained so that the "best-fit" line (given the constraint) fits worse than a horizontal line. With nonlinear regression, the R2 can be negative whenever the best-fit model (given the chosen equation, and its constraints, if any) fits the data worse than a horizontal line.

Bottom line: a negative R2 is not a mathematical impossibility or the sign of a computer bug. It simply means that the chosen model (with its constraints) fits the data really poorly.

In [17]:
from pathlib import Path
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [18]:
#data = Path('./Resources/combined_data.csv')
data = Path('./Resources/topfive_lepidoptera.csv')
df = pd.read_csv(data)
df.head()

order_name  family_name    datetime  individuals  tempmax  tempmin  \
0  LEPIDOPTERA  GEOMETRIDAE  1995-06-25            4     77.1     56.0   
1  LEPIDOPTERA  GEOMETRIDAE  1995-06-27            3     69.9     57.3   
2  LEPIDOPTERA  GEOMETRIDAE  2006-07-20            1     82.4     66.1   
3  LEPIDOPTERA  GEOMETRIDAE  2006-06-13            1     79.6     59.9   
4  LEPIDOPTERA  GEOMETRIDAE  1995-07-17            1     71.5     59.1   

   temp_daily  humidity  
0        67.4      60.0  
1        63.7      54.5  
2        73.8      68.3  
3        71.1      55.6  
4        65.1      73.8

In [19]:
# Segment the features from the target
y = df["individuals"]
#X = df.drop(columns=["order_name", "family_name", "datetime", "individuals", "tempmax","tempmin"])
X = df.drop(columns=["order_name", "family_name", "datetime", "individuals", "tempmax","tempmin", "temp_daily"])

In [20]:
# Use the train_test_split function to create training and testing subsets
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y,test_size=0.2, random_state=42)
X_train.shape

(21800, 1)

In [21]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators= 10, random_state= 0)
regressor.fit(X_train, y_train)

RandomForestRegressor(n_estimators=10, random_state=0)

In [22]:
y_pred = regressor.predict(X_test)

y_pred

array([5.34970746, 3.86650165, 5.97984725, ..., 4.13892474, 4.50068853,
       6.8444261 ])

In [23]:
from sklearn.metrics import r2_score
r2_score(y_test, y_pred)

-0.010469840579926837

https://stats.stackexchange.com/questions/12900/when-is-r-squared-negative

R2  compares the fit of the chosen model with that of a horizontal straight line (the null hypothesis). If the chosen model fits worse than a horizontal line, then R2 is negative. Note that R2 is not always the square of anything, so it can have a negative value without violating any rules of math. R2 is negative only when the chosen model does not follow the trend of the data, so fits worse than a horizontal line.

Example: fit data to a linear regression model constrained so that the Y intercept must equal 1500.

enter image description here

The model makes no sense at all given these data. It is clearly the wrong model, perhaps chosen by accident.

The fit of the model (a straight line constrained to go through the point (0,1500)) is worse than the fit of a horizontal line. Thus the sum-of-squares from the model (SSres) is larger than the sum-of-squares from the horizontal line (SStot).

If R2 is computed as 1−SSresSStot. (here, SSres = residual error.)
When SSres is greater than SStot, that equation could compute a negative value for R2, if the value of the coeficient is greater than 1.

With linear regression with no constraints, R2 must be positive (or zero) and equals the square of the correlation coefficient, r. A negative R2 is only possible with linear regression when either the intercept or the slope are constrained so that the "best-fit" line (given the constraint) fits worse than a horizontal line. With nonlinear regression, the R2 can be negative whenever the best-fit model (given the chosen equation, and its constraints, if any) fits the data worse than a horizontal line.

Bottom line: a negative R2 is not a mathematical impossibility or the sign of a computer bug. It simply means that the chosen model (with its constraints) fits the data really poorly.